// AUTO-GENERATED by scratchpad/vendor-logos.mjs — do not edit by hand.
// Local logo assets vendored into public/token-logos/ and public/chain-logos/ so
// the wallet renders icons instantly with no CDN round-trip (and no per-render
// CDN race). Tokens are keyed by canonical slug (alias-resolved, lowercased,
// stripped); chains by our network id. Anything NOT listed here falls back to the
// CDN resolvers in Icons.tsx exactly as before. Regenerate with the vendor script.

export const VENDORED_TOKENS: ReadonlySet<string> = new Set([
  "1inch", "aave", "ada", "aero", "aioz", "akt", "algo", "ankr", "ape", "apt", "ar", "arb", "atom", "avax", "axs", "bal", "bat", "bch", "beam", "bgb", "blast", "bnb", "bonk", "brett", "btc", "btcb", "busd", "cake", "celo", "cfg", "chz", "ckb", "comp", "cro", "crv", "cusd", "cvx", "dai", "dash", "dexe", "dgb", "doge", "dot", "dydx", "egld", "eigen", "enj", "ens", "eos", "etc", "eth", "ethfi", "fdusd", "fet", "fil", "floki", "flow", "frax", "ftm", "fxs", "gala", "gas", "grt", "gt", "gusd", "hbar", "hnt", "hot", "ht", "icp", "ilv", "imx", "inj", "jasmy", "joe", "jup", "kas", "kava", "kcs", "klay", "ksm", "ldo", "leo", "link", "lrc", "ltc", "lusd", "mana", "matic", "metis", "mkr", "mnt", "mog", "morpho", "mx", "near", "neo", "nmr", "not", "okb", "om", "ondo", "one", "op", "osmo", "paxg", "pendle", "pepe", "pol", "pyth", "pyusd", "qnt", "quick", "ray", "render", "reth", "rose", "rpl", "rune", "rvn", "sand", "scroll", "sei", "shib", "sky", "snx", "sol", "spx", "steth", "strk", "sui", "super", "susd", "sushi", "tao", "tbtc", "theta", "tia", "ton", "trx", "tusd", "uni", "usd0", "usdc", "usdd", "usde", "usdp", "usdt", "velo", "vet", "wbnb", "wbtc", "weeth", "weth", "wif", "wld", "woo", "wsteth", "xaut", "xlm", "xmr", "xrp", "xtz", "ygg", "zec", "zil", "zk",
]);

export const VENDORED_CHAINS: ReadonlySet<string> = new Set([
  "arbitrum", "aurora", "avalanche", "bitcoin", "blast", "bsc", "celo", "cronos", "ethereum", "fantom", "gnosis", "klaytn", "linea", "litecoin", "mantle", "metis", "moonbeam", "optimism", "polygon", "polygonzkevm", "scroll", "sei", "solana", "sui", "tron", "xrp", "zksync",
]);
