/**
 * NumPay unified icon registry — single source of truth.
 *
 * Ported verbatim from the Claude Design handoff (`design_handoff_icons`).
 * One canonical icon PER ticker symbol, identical on every chain; chain is only
 * ever a corner badge. `brand[SYMBOL]` describes the deterministic fallback coin
 * used when no streamed logo is available:
 *   disc  = disc fill (token brand colour)
 *   mark  = override mark colour (else auto-contrast from disc)
 *   glyph = drawn glyph key in iconGlyphs.ts
 *   char  = single font glyph used as the mark (e.g. a currency sign)
 *   mono  = monogram override (else first 1-4 chars of the symbol)
 * No brand entry -> deterministic hash palette + monogram.
 */

export interface BrandEntry {
  disc: string;
  mark?: string;
  glyph?: string;
  char?: string;
  mono?: string;
}

export interface ChainEntry extends BrandEntry {
  label: string;
}

export interface IconData {
  palette: string[];
  tokens: Record<string, string[]>;
  brand: Record<string, BrandEntry>;
  chains: Record<string, ChainEntry>;
  /** Per-symbol pinned brand logos (curated). Local paths resolve via the
   *  extension URL; values starting with http(s) are used as-is. Highest
   *  priority in token logo resolution, above the streamed CDN logo. */
  logoOverrides: Record<string, string>;
  aliases: Record<string, string>;
}

export const ICON_DATA: IconData = {
  palette: [
    "#4F46E5", "#2563EB", "#0E7490", "#0F766E", "#15803D", "#3F6212",
    "#B45309", "#C2410C", "#B91C1C", "#BE123C", "#A21CAF", "#7E22CE",
    "#6D28D9", "#1D4ED8", "#0369A1", "#047857", "#166534", "#92400E",
    "#9F1239", "#5B21B6", "#1E40AF", "#155E75", "#831843", "#3730A3",
  ],
  tokens: {
    "Native L1 / L2": [
      "BTC", "ETH", "BNB", "SOL", "XRP", "ADA", "AVAX", "DOGE", "TRX", "DOT",
      "MATIC", "POL", "LTC", "BCH", "TON", "ATOM", "NEAR", "APT", "SUI", "SEI",
      "TIA", "INJ", "FTM", "S", "CRO", "ALGO", "EGLD", "FLOW", "HBAR", "ICP",
      "KAS", "XLM", "XMR", "ETC", "FIL", "VET", "RUNE", "KAVA", "ROSE", "ONE",
      "CELO", "GLMR", "METIS", "MNT", "KLAY", "ZK", "STRK", "MANTA", "BLAST",
      "SCROLL", "ARB", "OP", "IMX", "ZEC", "DASH", "XTZ", "EOS", "NEO", "THETA",
      "IOTA", "QNT", "CKB", "ASTR", "KSM",
    ],
    Stablecoins: [
      "USDT", "USDC", "DAI", "FDUSD", "TUSD", "USDP", "BUSD", "FRAX", "USDD",
      "GUSD", "LUSD", "SUSD", "USDE", "PYUSD", "CRVUSD", "CUSD", "EURC", "USDS",
      "USD0", "GHO",
    ],
    "Wrapped & Liquid Staking": [
      "WETH", "WBTC", "WBNB", "WAVAX", "WMATIC", "WSOL", "BTCB", "TBTC", "STETH",
      "WSTETH", "RETH", "CBETH", "WEETH", "EZETH", "SFRXETH", "MSOL", "JITOSOL",
      "JUPSOL", "SAVAX", "BETH",
    ],
    "DeFi Blue Chips": [
      "UNI", "LINK", "AAVE", "MKR", "SKY", "CRV", "CVX", "LDO", "SNX", "COMP",
      "SUSHI", "BAL", "YFI", "1INCH", "DYDX", "GMX", "PENDLE", "MORPHO", "ETHFI",
      "EIGEN", "RPL", "FXS", "ENS", "JUP", "RAY", "ORCA", "JTO", "DRIFT", "KMNO",
      "PYTH", "W", "ZRO", "STG", "LRC", "DEXE", "CAKE", "AERO", "VELO", "JOE",
      "QUICK", "OSMO",
    ],
    "AI & DePIN": [
      "FET", "RENDER", "TAO", "AKT", "WLD", "IO", "AIOZ", "NMR", "ARKM", "GRT",
      "AR", "HNT",
    ],
    "Gaming & Metaverse": [
      "SAND", "MANA", "AXS", "GALA", "ENJ", "GMT", "MAGIC", "PRIME", "BEAM",
      "RON", "PIXEL", "ILV", "YGG", "SUPER", "APE", "BIGTIME",
    ],
    Memecoins: [
      "SHIB", "PEPE", "WIF", "BONK", "FLOKI", "BABYDOGE", "BRETT", "POPCAT",
      "MOG", "TURBO", "MEW", "BOME", "GIGA", "PNUT", "GOAT", "SPX", "DEGEN",
      "TOSHI", "NEIRO", "MOODENG", "FARTCOIN",
    ],
    "Exchange & CeFi": [
      "OKB", "BGB", "GT", "KCS", "MX", "WOO", "LEO", "HT",
    ],
    "RWA & Other Majors": [
      "ONDO", "PAXG", "XAUT", "OM", "POLYX", "CFG", "JASMY", "CHZ", "BAT",
      "ANKR", "GAS", "ZIL", "RVN", "DGB", "HOT", "NOT", "DOGS", "HMSTR",
    ],
  },
  brand: {
    BTC: { disc: "#F7931A", char: "₿" },
    ETH: { disc: "#627EEA", glyph: "eth" },
    BNB: { disc: "#F3BA2F", glyph: "bnb", mark: "#16181E" },
    SOL: { disc: "#0B0E11", glyph: "sol", mark: "#14F195" },
    XRP: { disc: "#23292F", glyph: "xrp" },
    ADA: { disc: "#0033AD" },
    AVAX: { disc: "#E84142", glyph: "avax" },
    DOGE: { disc: "#C2A633", char: "Ð", mark: "#16181E" },
    TRX: { disc: "#EF0027" },
    DOT: { disc: "#E6007A", glyph: "dot" },
    MATIC: { disc: "#8247E5" },
    POL: { disc: "#6C00F6" },
    LTC: { disc: "#345D9D", char: "Ł" },
    BCH: { disc: "#0AC18E" },
    TON: { disc: "#0098EA", glyph: "ton" },
    ATOM: { disc: "#2E3148", glyph: "atom" },
    NEAR: { disc: "#131313" },
    APT: { disc: "#0E1111" },
    SUI: { disc: "#4DA2FF" },
    SEI: { disc: "#9E1F19" },
    TIA: { disc: "#7B2BF9" },
    INJ: { disc: "#00A3FF" },
    FTM: { disc: "#1969FF" },
    S: { disc: "#F4631E" },
    CRO: { disc: "#103F68" },
    ALGO: { disc: "#0A0A0A" },
    EGLD: { disc: "#1B46C2" },
    FLOW: { disc: "#00C271", mark: "#16181E" },
    HBAR: { disc: "#0A0A0A" },
    ICP: { disc: "#29ABE2" },
    KAS: { disc: "#4FB8AC", mark: "#0A0A0A" },
    XLM: { disc: "#0A0A0A" },
    XMR: { disc: "#FF6600", char: "ɱ", mark: "#16181E" },
    ETC: { disc: "#328332" },
    FIL: { disc: "#0090FF" },
    VET: { disc: "#15BDFF", mark: "#0A0A0A" },
    RUNE: { disc: "#1FC29F", mark: "#0A0A0A" },
    KAVA: { disc: "#FF433E" },
    ROSE: { disc: "#0500E1" },
    ONE: { disc: "#00AEE9", mark: "#0A0A0A" },
    CELO: { disc: "#FBCC5C", mark: "#16181E" },
    GLMR: { disc: "#E1147B" },
    METIS: { disc: "#00BFB4", mark: "#0A0A0A" },
    MNT: { disc: "#0A0A0A" },
    KLAY: { disc: "#F04706" },
    ZK: { disc: "#1E69FF" },
    STRK: { disc: "#0C0C4F" },
    MANTA: { disc: "#2D44FB" },
    BLAST: { disc: "#FCFC03", mark: "#16181E" },
    SCROLL: { disc: "#E7C49A", mark: "#16181E" },
    ARB: { disc: "#28A0F0" },
    OP: { disc: "#FF0420" },
    IMX: { disc: "#0B0E11" },
    ZEC: { disc: "#ECB244", mark: "#16181E" },
    DASH: { disc: "#008CE7" },
    XTZ: { disc: "#2C7DF7" },
    EOS: { disc: "#0A0A0A" },
    NEO: { disc: "#00C26B", mark: "#0A0A0A" },
    THETA: { disc: "#2AB8E6" },
    IOTA: { disc: "#131F37" },
    QNT: { disc: "#0A0A0A" },
    CKB: { disc: "#3CC68A", mark: "#0A0A0A" },
    ASTR: { disc: "#0070EB" },
    KSM: { disc: "#0A0A0A" },

    USDT: { disc: "#26A17B", glyph: "usdt" },
    USDC: { disc: "#2775CA", glyph: "usdc" },
    DAI: { disc: "#F5AC37", glyph: "dai", mark: "#FFFFFF" },
    FDUSD: { disc: "#00A478" },
    TUSD: { disc: "#1B81F4" },
    USDP: { disc: "#00997B" },
    BUSD: { disc: "#F0B90B", mark: "#16181E" },
    FRAX: { disc: "#0A0A0A" },
    USDD: { disc: "#3D9B35" },
    GUSD: { disc: "#26C5E8", mark: "#16181E" },
    LUSD: { disc: "#745DDF" },
    SUSD: { disc: "#1E9FD6" },
    USDE: { disc: "#0A0A0A" },
    PYUSD: { disc: "#00A8E0" },
    CRVUSD: { disc: "#3667A6" },
    CUSD: { disc: "#35D07F", mark: "#16181E" },
    EURC: { disc: "#2775CA", char: "€" },
    USDS: { disc: "#16181E" },
    USD0: { disc: "#1455F0" },
    GHO: { disc: "#2EBAC6", mark: "#16181E" },

    WETH: { disc: "#627EEA" },
    WBTC: { disc: "#F7931A" },
    WBNB: { disc: "#F3BA2F", mark: "#16181E" },
    WAVAX: { disc: "#E84142" },
    WMATIC: { disc: "#8247E5" },
    WSOL: { disc: "#0B0E11", mark: "#14F195" },
    BTCB: { disc: "#F7931A" },
    TBTC: { disc: "#5B3FE8" },
    STETH: { disc: "#00A3FF" },
    WSTETH: { disc: "#00A3FF" },
    RETH: { disc: "#FF6C56" },
    CBETH: { disc: "#0052FF" },
    WEETH: { disc: "#4A2CF0" },
    EZETH: { disc: "#1A4DFF" },
    SFRXETH: { disc: "#0A0A0A" },
    MSOL: { disc: "#9945FF" },
    JITOSOL: { disc: "#14B85F" },
    JUPSOL: { disc: "#2EBD85" },
    SAVAX: { disc: "#E84142" },
    BETH: { disc: "#F3BA2F", mark: "#16181E" },

    UNI: { disc: "#FF007A" },
    LINK: { disc: "#2A5ADA", glyph: "link" },
    AAVE: { disc: "#B6509E" },
    MKR: { disc: "#1AAB9B" },
    SKY: { disc: "#F7D046", mark: "#16181E" },
    CRV: { disc: "#3667A6" },
    CVX: { disc: "#1682FE" },
    LDO: { disc: "#00A3FF" },
    SNX: { disc: "#1E9FD6" },
    COMP: { disc: "#00D395", mark: "#16181E" },
    SUSHI: { disc: "#FA52A0" },
    BAL: { disc: "#1E1E1E" },
    YFI: { disc: "#006AE3" },
    "1INCH": { disc: "#1B314F" },
    DYDX: { disc: "#6966FF" },
    GMX: { disc: "#2D42FC" },
    PENDLE: { disc: "#1FAE94", mark: "#16181E" },
    MORPHO: { disc: "#2563EB" },
    ETHFI: { disc: "#4A2CF0" },
    EIGEN: { disc: "#1A0C6D" },
    RPL: { disc: "#FF6C56" },
    FXS: { disc: "#0A0A0A" },
    ENS: { disc: "#5298FF" },
    JUP: { disc: "#2EBD85" },
    RAY: { disc: "#3772FF" },
    ORCA: { disc: "#FFD15C", mark: "#16181E" },
    JTO: { disc: "#14B85F" },
    DRIFT: { disc: "#7C5CFF" },
    KMNO: { disc: "#E8643C" },
    PYTH: { disc: "#7142CF" },
    W: { disc: "#2D2F64" },
    ZRO: { disc: "#0A0A0A" },
    STG: { disc: "#16181E" },
    LRC: { disc: "#1C60FF" },
    DEXE: { disc: "#0A0A0A" },
    CAKE: { disc: "#D1884F" },
    AERO: { disc: "#0433FF" },
    VELO: { disc: "#1B5BFF" },
    JOE: { disc: "#F0443E" },
    QUICK: { disc: "#418ACA" },
    OSMO: { disc: "#5E12A0" },

    FET: { disc: "#2E2E5C" },
    RENDER: { disc: "#E0093E" },
    TAO: { disc: "#0A0A0A" },
    AKT: { disc: "#E2231A" },
    WLD: { disc: "#0A0A0A" },
    IO: { disc: "#1A1A1A" },
    AIOZ: { disc: "#0047FF" },
    NMR: { disc: "#0A0A0A" },
    ARKM: { disc: "#0F1419" },
    GRT: { disc: "#6747ED" },
    AR: { disc: "#0A0A0A" },
    HNT: { disc: "#474DFF" },

    SAND: { disc: "#00ADEF" },
    MANA: { disc: "#FF2D55" },
    AXS: { disc: "#0055D5" },
    GALA: { disc: "#0A0A0A" },
    ENJ: { disc: "#7866D5" },
    GMT: { disc: "#B8945A", mark: "#16181E" },
    MAGIC: { disc: "#DC2B36" },
    PRIME: { disc: "#0A0A0A" },
    BEAM: { disc: "#0A0A0A" },
    RON: { disc: "#1273EA" },
    PIXEL: { disc: "#3B82F6" },
    ILV: { disc: "#4A35DE" },
    YGG: { disc: "#1F3BE0" },
    SUPER: { disc: "#E11D63" },
    APE: { disc: "#0054F9" },
    BIGTIME: { disc: "#E8A33D", mark: "#16181E" },

    SHIB: { disc: "#F09712", mark: "#16181E" },
    PEPE: { disc: "#3D8130" },
    WIF: { disc: "#BC9763", mark: "#16181E" },
    BONK: { disc: "#F09700", mark: "#16181E" },
    FLOKI: { disc: "#F4900C", mark: "#16181E" },
    BABYDOGE: { disc: "#F2BE3A", mark: "#16181E" },
    BRETT: { disc: "#2A5ADA" },
    POPCAT: { disc: "#D9963B", mark: "#16181E" },
    MOG: { disc: "#6747ED" },
    TURBO: { disc: "#16181E" },
    MEW: { disc: "#E86AA0" },
    BOME: { disc: "#C0392B" },
    GIGA: { disc: "#8A6D3B" },
    PNUT: { disc: "#C8663E" },
    GOAT: { disc: "#6B4E2E" },
    SPX: { disc: "#E0093E" },
    DEGEN: { disc: "#8A5CF6" },
    TOSHI: { disc: "#2A5ADA" },
    NEIRO: { disc: "#E0903A", mark: "#16181E" },
    MOODENG: { disc: "#E07A3E" },
    FARTCOIN: { disc: "#C29A4E", mark: "#16181E" },

    OKB: { disc: "#0A0A0A" },
    BGB: { disc: "#00B47E" },
    GT: { disc: "#16181E" },
    KCS: { disc: "#23D6A0", mark: "#16181E" },
    MX: { disc: "#2354E6" },
    WOO: { disc: "#16181E" },
    LEO: { disc: "#16327E" },
    HT: { disc: "#2A4ED6" },

    ONDO: { disc: "#16181E" },
    PAXG: { disc: "#DBB04A", mark: "#16181E" },
    XAUT: { disc: "#C5A040", mark: "#16181E" },
    OM: { disc: "#2D2D2D" },
    POLYX: { disc: "#4D27D6" },
    CFG: { disc: "#1A1A1A" },
    JASMY: { disc: "#1A1A1A" },
    CHZ: { disc: "#CD0124" },
    BAT: { disc: "#FF5000" },
    ANKR: { disc: "#2972FF" },
    GAS: { disc: "#00C26B", mark: "#16181E" },
    ZIL: { disc: "#3AB6B0", mark: "#16181E" },
    RVN: { disc: "#384182" },
    DGB: { disc: "#0066CC" },
    HOT: { disc: "#11B3D6" },
    NOT: { disc: "#0A0A0A" },
    DOGS: { disc: "#E0903A", mark: "#16181E" },
    HMSTR: { disc: "#E0903A", mark: "#16181E" },
  },
  chains: {
    ethereum: { label: "Ethereum", disc: "#627EEA", glyph: "eth" },
    sepolia: { label: "Sepolia", disc: "#627EEA", glyph: "eth" },
    polygon: { label: "Polygon", disc: "#8247E5", mono: "POL" },
    arbitrum: { label: "Arbitrum", disc: "#28A0F0", mono: "ARB" },
    optimism: { label: "Optimism", disc: "#FF0420", mono: "OP" },
    base: { label: "Base", disc: "#0052FF", mono: "BASE" },
    avalanche: { label: "Avalanche", disc: "#E84142", glyph: "avax" },
    bsc: { label: "BNB Chain", disc: "#F3BA2F", glyph: "bnb", mark: "#16181E" },
    zksync: { label: "zkSync Era", disc: "#16181E", mono: "ZK" },
    scroll: { label: "Scroll", disc: "#E7C49A", mark: "#16181E", mono: "SCR" },
    linea: { label: "Linea", disc: "#16181E", mono: "LINEA" },
    mantle: { label: "Mantle", disc: "#0A0A0A", mono: "MNT" },
    blast: { label: "Blast", disc: "#FCFC03", mark: "#16181E", mono: "BLAST" },
    polygonzkevm: { label: "Polygon zkEVM", disc: "#8247E5", mono: "ZK" },
    fantom: { label: "Fantom", disc: "#1969FF", mono: "FTM" },
    cronos: { label: "Cronos", disc: "#103F68", mono: "CRO" },
    celo: { label: "Celo", disc: "#FBCC5C", mark: "#16181E", mono: "CELO" },
    gnosis: { label: "Gnosis", disc: "#04795B", mono: "GNO" },
    moonbeam: { label: "Moonbeam", disc: "#E1147B", mono: "MOON" },
    aurora: { label: "Aurora", disc: "#6FD44B", mark: "#16181E", mono: "AUR" },
    sei: { label: "Sei", disc: "#9E1F19", mono: "SEI" },
    klaytn: { label: "Klaytn", disc: "#F04706", mono: "KLAY" },
    metis: { label: "Metis", disc: "#00BFB4", mark: "#16181E", mono: "MTS" },
    solana: { label: "Solana", disc: "#0B0E11", glyph: "sol", mark: "#14F195" },
    bitcoin: { label: "Bitcoin", disc: "#F7931A", char: "₿" },
    tron: { label: "Tron", disc: "#EF0027", mono: "TRX" },
    xrp: { label: "XRP Ledger", disc: "#23292F", glyph: "xrp" },
    sui: { label: "Sui", disc: "#4DA2FF", mono: "SUI" },
    litecoin: { label: "Litecoin", disc: "#345D9D", char: "Ł" },
  },
  logoOverrides: {
    POL: "https://coin-images.coingecko.com/coins/images/32440/large/polygon.png",
    TON: "https://coin-images.coingecko.com/coins/images/17980/large/ton_symbol.png",
    BLAST: "token-logos/blast.png",
    SCROLL: "token-logos/scroll.png",
    USDC: "token-logos/usdc.png",
  },
  // POL is its own entry (its own brand + override) — do NOT alias it to MATIC.
  aliases: {
    WPOL: "WMATIC", XBT: "BTC", MIOTA: "IOTA",
    KAIA: "KLAY", RNDR: "RENDER", MATICPOS: "MATIC", USDTE: "USDT",
    USDCE: "USDC", WAVAXE: "WAVAX", ETH2: "ETH",
  },
};
